CREATE TABLE IF NOT EXISTS Pais (
    idPais INTEGER PRIMARY KEY AUTOINCREMENT,
    Pais TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Usuario (
    idUsuario INTEGER PRIMARY KEY AUTOINCREMENT,
    Nombre TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Registro (
    idRegistro INTEGER PRIMARY KEY AUTOINCREMENT,
    idUsuario INTEGER NOT NULL,
    idPais INTEGER NOT NULL,
    dateEntrada TEXT NOT NULL,
    dateSalida TEXT NOT NULL,
    FOREIGN KEY (idUsuario) REFERENCES Usuario(idUsuario),
    FOREIGN KEY (idPais) REFERENCES Pais(idPais)
);

